baseURL = 'https://rctv.com/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = 'RCTV â€” AI Video & Media Intelligence'
enableRobotsTXT = true
googleAnalytics = 'G-9LX5G8MV0X'

# List Config
summaryLength= 15
[pagination]
  pagerSize = 5

# Custom CSS
calloutCSS = ["css/callout.css"]
