[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "roundup"
    name = "Weekly Roundup"
    url = "/categories/weekly-roundup"
    weight = 2

[[main]]
    identifier = "posts"
    name = "Archive"
    url = "/posts"
    weight = 3

[[main]]
    identifier = "about"
    name = "About"
    url = "/posts/about"
    weight = 5